### PR TITLE
Fix script for firmware version 1.5.4

### LINKED ISSUE #2: Could not decrypt data from hs110
Hi, I am using the py script on Ubuntu against two new HS110 devices and receiving "Could not decrypt data from hs110" message.
After this message appears about 6 or 7 times I then get "Could not connect to host 192.168.1.15:9999" once or twice and then the  "Could not decrypt data from hs110" message returns again.
This just happens over and over in a loop, almost as if the device restarts after several failed attempts to scrap the data from it?

The hardware version of my hs110 devices is 2.0 and the Firmware version is 1.5.2.

I'm wondering if this new firmware has made some changes preventing the script from working? Can I ask what firmware your devices are using or any other troubleshooting steps?

Looking for any advice to troubleshoot this?
Thanks!

### PR DESCRIPTION
**Pull request by ottojo**
adds "total" measurement
changes json fields to include unit
fixes encryption routine (taken from softScheck/tplink-smartplug@7fabe4574c306496224feccf71b65f15802cfcd7)

I think this will also fix #2, my HS110 is hardware version 2.0, firmware version 1.5.4

### CODE REVIEW

**Comment by sdelrio** [comment]
The problem is that return value is like this
```
{u'emeter': {u'get_realtime': {u'current': 0.043542, u'total': 296.866, u'voltage': 236.104744, u'power': 0.715639, u'err_code': 0}}}
````

So it will give a Key exception because power_mw is not found:
```
$ ./hs110-exporter.py -t $HS110IP -f 1 -p 8110

Traceback (most recent call last):
  File "./hs110-exporter.py", line 122, in <module>
    print "IP: " + ip + ":" + str(port) + " Received power: " + str(received_data["emeter"]["get_realtime"]["power_mw"])
KeyError: 'power_mw'
```
I have Hardware version 1.0, had firmware version 1.1.10 at the begining but upgraded to 1.2.5, what are your version? if it changed perhaps should add a paramiter for each version.

**Comment by sdelrio** [comment]
> The problem is that return value is like this
> 
> ```
> {u'emeter': {u'get_realtime': {u'current': 0.043542, u'total': 296.866, u'voltage': 236.104744, u'power': 0.715639, u'err_code': 0}}}
> ```
> So it will give a Key exception because power_mw is not found:
> 
> ```
> $ ./hs110-exporter.py -t $HS110IP -f 1 -p 8110
> 
> Traceback (most recent call last):
>   File "./hs110-exporter.py", line 122, in <module>
>     print "IP: " + ip + ":" + str(port) + " Received power: " + str(received_data["emeter"]["get_realtime"]["power_mw"])
> KeyError: 'power_mw'
> ```
> I have Hardware version 1.0, had firmware version 1.1.10 at the begining but upgraded to 1.2.5, what are your version? if it changed perhaps should add a paramiter for each version.

Sorry, didn't saw your last line
 version 2.0, firmware version 1.5.4

**Comment by sdelrio** [comment]
Let me try to detect the suffix and change it depending on where connect without adding an extra parameter, I will commit to the PR.

**Comment by sdelrio** [comment]
I've just made a commit and push to your branch, check it on your hardware version 2 and update this PR so I can merge. On hs110 hardware 1 it works.

https://github.com/sdelrio/hs110-prometheus-exporter/commit/4a9577ad4c032db118b34740659331cc9831cec6

**Comment by ottojo** [comment]
It works very nicely! I've added the commit to my branch.

**Comment by sdelrio** [comment]
Nice, merging it.

**Pull request merged**
